apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-03-18T09:12:04Z"
  generation: 2
  labels:
    app: hartmann-klausur
  name: hartmann-klausur
  namespace: maximilian-hartmann
  resourceVersion: "261207"
  uid: a43bd5ac-117e-4b4c-989d-9068ab5f98ee
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hartmann-klausur
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hartmann-klausur
    spec:
      containers:
      - image: ghcr.io/ci-cd-2024-dhbw-hdh/maximilian.hartmann:latest
        imagePullPolicy: Always
        name: maximilian-hartmann-84j9p
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-03-18T09:17:23Z"
    lastUpdateTime: "2024-03-18T09:17:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-03-18T09:12:04Z"
    lastUpdateTime: "2024-03-18T09:17:23Z"
    message: ReplicaSet "hartmann-klausur-5f97b78dd7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
