name: cicd pipeline
run-name: ${{ github.actor }} is pushing on master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build 
        run: |
          npm ci
          npm install
          npm run build

      - name: Test
        run: npm run test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist