name: Digital Ocean Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Create namespace
        run: kubectl create namespace maximilian-hartmann --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy
        run: |
          kubectl apply -n maximilian-hartmann -f deployment/deployment.yaml
          kubectl apply -n maximilian-hartmann -f deployment/service.yaml
      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          namespace: 'maximilian-hartmann'
          secret-name: 'regcred'
          container-registry-url: 'ghcr.io'
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.PULL_TOKEN }}
        id: create-secret